
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class ContactType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ContactType()
    {

        this.Contact = new HashSet<Contact>();

    }


    public int cnttp_id { get; set; }

    public string cnttp_name { get; set; }

    public bool cnttp_state { get; set; }

    public Nullable<System.DateTime> cnttp_registrationDate { get; set; }

    public Nullable<System.DateTime> cnttp_updateDate { get; set; }

    public Nullable<System.DateTime> cnttp_deleteDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Contact> Contact { get; set; }

}

}
