//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_FleetService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.VehicleModelsByContract = new HashSet<VehicleModelsByContract>();
            this.VehiclesByContract = new HashSet<VehiclesByContract>();
        }
    
        public int cntr_id { get; set; }
        public Nullable<int> cntr_consecutive { get; set; }
        public string cntr_code { get; set; }
        public string cntr_name { get; set; }
        public string cntr_observation { get; set; }
        public Nullable<int> deal_id { get; set; }
        public Nullable<int> cli_id { get; set; }
        public Nullable<int> cntrst_id { get; set; }
        public Nullable<bool> cntr_state { get; set; }
        public Nullable<int> dst_id { get; set; }
        public Nullable<int> cntr_discountValue { get; set; }
        public int cntr_amountOfMaintenances { get; set; }
        public Nullable<System.DateTime> cntr_startingDate { get; set; }
        public Nullable<System.DateTime> cntr_endingDate { get; set; }
        public Nullable<int> cntr_duration { get; set; }
        public Nullable<System.DateTime> cntr_registrationDate { get; set; }
        public Nullable<System.DateTime> cntr_updateDate { get; set; }
        public Nullable<System.DateTime> cntr_deleteDate { get; set; }
        public Nullable<int> cntr_amountVehicles { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ContractState ContractState { get; set; }
        public virtual Dealer Dealer { get; set; }
        public virtual DiscountType DiscountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleModelsByContract> VehicleModelsByContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehiclesByContract> VehiclesByContract { get; set; }
    }
}
