
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class ContractState
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ContractState()
    {

        this.Contract = new HashSet<Contract>();

    }


    public int cntrst_id { get; set; }

    public string cntrst_name { get; set; }

    public string cntrst_description { get; set; }

    public Nullable<bool> cntrst_state { get; set; }

    public Nullable<System.DateTime> cntrst_registrationDate { get; set; }

    public Nullable<System.DateTime> cntrst_updateDate { get; set; }

    public Nullable<System.DateTime> cntrst_deleteDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Contract> Contract { get; set; }

}

}
