
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class ContractualInformationByClient
{

    public int cntInf_id { get; set; }

    public int cli_id { get; set; }

    public string cntInf_contractCode { get; set; }

    public Nullable<System.DateTime> cntInf_serviceInitDate { get; set; }

    public Nullable<System.DateTime> cntInf_serviceEndDate { get; set; }

    public Nullable<System.DateTime> cntInf_quotaApprovalDate { get; set; }

    public Nullable<System.DateTime> cntInf_quotaEndingDate { get; set; }

    public Nullable<int> qt_id { get; set; }

    public Nullable<short> cntInf_paymentAgreement { get; set; }

    public Nullable<byte> cntInf_adminPercentage { get; set; }

    public int usr_id { get; set; }

    public Nullable<bool> cntInf_state { get; set; }

    public Nullable<System.DateTime> cntInf_registrationDate { get; set; }

    public Nullable<System.DateTime> cntInf_updateDate { get; set; }

    public Nullable<System.DateTime> cntInf_deleteDate { get; set; }



    public virtual Client Client { get; set; }

    public virtual QuotaType QuotaType { get; set; }

    public virtual Users Users { get; set; }

}

}
