
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class DealerNetwork
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DealerNetwork()
    {

        this.DealerByDealerNerwork = new HashSet<DealerByDealerNerwork>();

    }


    public int dn_id { get; set; }

    public string dn_name { get; set; }

    public Nullable<bool> dn_state { get; set; }

    public Nullable<System.DateTime> dn_registrationDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DealerByDealerNerwork> DealerByDealerNerwork { get; set; }

}

}
