
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class DealerByDealerNerwork
{

    public int dbdn_id { get; set; }

    public Nullable<int> dn_id { get; set; }

    public Nullable<int> deal_id { get; set; }



    public virtual Dealer Dealer { get; set; }

    public virtual DealerNetwork DealerNetwork { get; set; }

}

}
