
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class FieldsToOperate
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FieldsToOperate()
    {

        this.RulesByMovement = new HashSet<RulesByMovement>();

        this.RulesByMovement1 = new HashSet<RulesByMovement>();

        this.RulesByMovement2 = new HashSet<RulesByMovement>();

    }


    public int fto_id { get; set; }

    public string fto_nameDb { get; set; }

    public string fto_nameToShow { get; set; }

    public Nullable<bool> fto_state { get; set; }

    public Nullable<System.DateTime> fto_registrationDate { get; set; }

    public Nullable<System.DateTime> fto_updateDate { get; set; }

    public Nullable<System.DateTime> fto_deleteDate { get; set; }

    public string fto_tableName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RulesByMovement> RulesByMovement { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RulesByMovement> RulesByMovement1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RulesByMovement> RulesByMovement2 { get; set; }

}

}
