
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class FinancialInformationByClient
{

    public int ficl_id { get; set; }

    public Nullable<int> cli_id { get; set; }

    public Nullable<double> ficl_approvedQuota { get; set; }

    public Nullable<double> ficl_consumedQuota { get; set; }

    public Nullable<double> ficl_currentQuota { get; set; }

    public Nullable<double> ficl_inTransitQuota { get; set; }

    public Nullable<bool> ficl_state { get; set; }

    public Nullable<System.DateTime> ficl_registrationDate { get; set; }

    public Nullable<System.DateTime> ficl_updateDate { get; set; }

    public Nullable<System.DateTime> ficl_deleteDate { get; set; }



    public virtual Client Client { get; set; }

}

}
