//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_FleetService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_FleetServiceEntities : DbContext
    {
        public DB_FleetServiceEntities()
            : base("name=DB_FleetServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<areas> areas { get; set; }
        public virtual DbSet<branch> branch { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Dealer> Dealer { get; set; }
        public virtual DbSet<DealerByDealerNerwork> DealerByDealerNerwork { get; set; }
        public virtual DbSet<DealerNetwork> DealerNetwork { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<jobTitle> jobTitle { get; set; }
        public virtual DbSet<JobTitlesClient> JobTitlesClient { get; set; }
        public virtual DbSet<Vehicle> Vehicle { get; set; }
        public virtual DbSet<VehicleBrand> VehicleBrand { get; set; }
        public virtual DbSet<VehicleModel> VehicleModel { get; set; }
        public virtual DbSet<VehicleType> VehicleType { get; set; }
        public virtual DbSet<vehicleState> vehicleState { get; set; }
        public virtual DbSet<MaintenanceItem> MaintenanceItem { get; set; }
        public virtual DbSet<PresentationUnit> PresentationUnit { get; set; }
        public virtual DbSet<TypeOfMaintenanceItem> TypeOfMaintenanceItem { get; set; }
        public virtual DbSet<frequency> frequency { get; set; }
        public virtual DbSet<maintenanceRoutine> maintenanceRoutine { get; set; }
        public virtual DbSet<MaintenanceItemCategory> MaintenanceItemCategory { get; set; }
        public virtual DbSet<MaintenanceItemsByVehicleModels> MaintenanceItemsByVehicleModels { get; set; }
        public virtual DbSet<MaintenanceItemsByVehicleTypes> MaintenanceItemsByVehicleTypes { get; set; }
        public virtual DbSet<ItemsByRoutines> ItemsByRoutines { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<ContractState> ContractState { get; set; }
        public virtual DbSet<DiscountType> DiscountType { get; set; }
        public virtual DbSet<VehicleModelsByContract> VehicleModelsByContract { get; set; }
        public virtual DbSet<VehiclesByContract> VehiclesByContract { get; set; }
        public virtual DbSet<Actions> Actions { get; set; }
        public virtual DbSet<GroupModule> GroupModule { get; set; }
        public virtual DbSet<GroupModuleAction> GroupModuleAction { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Company> Company { get; set; }
    }
}
