
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class frequency
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public frequency()
    {

        this.maintenanceRoutine = new HashSet<maintenanceRoutine>();

    }


    public int fq_id { get; set; }

    public string fq_name { get; set; }

    public Nullable<bool> fq_state { get; set; }

    public Nullable<System.DateTime> fq_registrationDate { get; set; }

    public Nullable<System.DateTime> fq_updateDate { get; set; }

    public Nullable<System.DateTime> fq_deleteDate { get; set; }

    public string fq_shortName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<maintenanceRoutine> maintenanceRoutine { get; set; }

}

}
