
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class ItemsByRoutines
{

    public int ibr_id { get; set; }

    public Nullable<int> mi_id { get; set; }

    public Nullable<int> mr_id { get; set; }

    public Nullable<float> mi_amount { get; set; }

    public Nullable<System.DateTime> ibr_registrationDate { get; set; }

    public Nullable<System.DateTime> ibr_updateDate { get; set; }



    public virtual MaintenanceItem MaintenanceItem { get; set; }

    public virtual MaintenanceItem MaintenanceItem1 { get; set; }

    public virtual maintenanceRoutine maintenanceRoutine { get; set; }

    public virtual maintenanceRoutine maintenanceRoutine1 { get; set; }

}

}
