
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class LOG_TRX
{

    public int ltrx_id { get; set; }

    public Nullable<int> trx_id { get; set; }

    public Nullable<double> ltrx_initApprovedQuota { get; set; }

    public Nullable<double> ltrx_initConsumedQuota { get; set; }

    public Nullable<double> ltrx_initCurrentQuota { get; set; }

    public Nullable<double> ltrx_initInTransitQuota { get; set; }

    public Nullable<double> ltrx_endApprovedQuota { get; set; }

    public Nullable<double> ltrx_endConsumedQuota { get; set; }

    public Nullable<double> ltrx_endCurrentQuota { get; set; }

    public Nullable<double> ltrx_endInTransitQuota { get; set; }

    public Nullable<System.DateTime> ltrx_registrationDate { get; set; }



    public virtual transactions transactions { get; set; }

}

}
