
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class maintenanceRoutine
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public maintenanceRoutine()
    {

        this.ItemsByRoutines = new HashSet<ItemsByRoutines>();

        this.ItemsByRoutines1 = new HashSet<ItemsByRoutines>();

        this.transactionDetail = new HashSet<transactionDetail>();

    }


    public int mr_id { get; set; }

    public string mr_name { get; set; }

    public string mr_description { get; set; }

    public Nullable<int> vm_id { get; set; }

    public Nullable<int> fq_id { get; set; }

    public Nullable<bool> mr_state { get; set; }

    public Nullable<System.DateTime> mr_registrationDate { get; set; }

    public Nullable<System.DateTime> mr_updateDate { get; set; }

    public Nullable<System.DateTime> mr_deleteDate { get; set; }

    public Nullable<float> mr_referencePrice { get; set; }



    public virtual VehicleModel VehicleModel { get; set; }

    public virtual frequency frequency { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ItemsByRoutines> ItemsByRoutines { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ItemsByRoutines> ItemsByRoutines1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<transactionDetail> transactionDetail { get; set; }

}

}
