
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class Movement
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Movement()
    {

        this.RulesByMovement = new HashSet<RulesByMovement>();

        this.transactions = new HashSet<transactions>();

    }


    public int m_id { get; set; }

    public string m_name { get; set; }

    public string m_description { get; set; }

    public Nullable<int> mtp_id { get; set; }

    public Nullable<bool> m_state { get; set; }

    public Nullable<System.DateTime> m_registrationDate { get; set; }

    public Nullable<System.DateTime> m_updateDate { get; set; }

    public Nullable<System.DateTime> m_deleteDate { get; set; }



    public virtual MovementType MovementType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RulesByMovement> RulesByMovement { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<transactions> transactions { get; set; }

}

}
