
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class MovementType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MovementType()
    {

        this.Movement = new HashSet<Movement>();

    }


    public int mtp_id { get; set; }

    public string mtp_name { get; set; }

    public string mtp_description { get; set; }

    public Nullable<System.DateTime> mtp_registrationDate { get; set; }

    public Nullable<System.DateTime> mtp_updateDate { get; set; }

    public Nullable<System.DateTime> mtp_deleteDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Movement> Movement { get; set; }

}

}
