
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class observationsByTransaction
{

    public int obstrx_id { get; set; }

    public Nullable<int> trx_id { get; set; }

    public string obstrx_description { get; set; }

    public Nullable<bool> obstrx_state { get; set; }

    public Nullable<System.DateTime> obstrx_registrationDate { get; set; }

    public Nullable<System.DateTime> obtrx_updateDate { get; set; }

    public Nullable<System.DateTime> obtrx_deleteDate { get; set; }

    public Nullable<int> usr_id { get; set; }



    public virtual transactions transactions { get; set; }

    public virtual Users Users { get; set; }

}

}
