
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class Operations
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Operations()
    {

        this.RulesByMovement = new HashSet<RulesByMovement>();

        this.RulesByMovement1 = new HashSet<RulesByMovement>();

    }


    public int op_id { get; set; }

    public string op_symbol { get; set; }

    public string op_name { get; set; }

    public Nullable<bool> op_state { get; set; }

    public Nullable<System.DateTime> op_registrationDate { get; set; }

    public Nullable<System.DateTime> op_updateDate { get; set; }

    public Nullable<System.DateTime> op_deleteDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RulesByMovement> RulesByMovement { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RulesByMovement> RulesByMovement1 { get; set; }

}

}
