
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class PricesByContract
{

    public int pbc_id { get; set; }

    public Nullable<int> cntr_id { get; set; }

    public Nullable<int> mi_id { get; set; }

    public Nullable<float> mi_referencePrice { get; set; }

    public Nullable<System.DateTime> pbc_registrationDate { get; set; }

    public Nullable<System.DateTime> pbc_updateDate { get; set; }

    public Nullable<System.DateTime> pbc_deleteDate { get; set; }



    public virtual Contract Contract { get; set; }

    public virtual MaintenanceItem MaintenanceItem { get; set; }

}

}
