
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class QuotaType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public QuotaType()
    {

        this.ContractualInformationByClient = new HashSet<ContractualInformationByClient>();

    }


    public int qt_id { get; set; }

    public string qt_name { get; set; }

    public string qt_description { get; set; }

    public Nullable<bool> qt_state { get; set; }

    public Nullable<System.DateTime> qt_registrationDate { get; set; }

    public Nullable<System.DateTime> qt_updateDate { get; set; }

    public Nullable<System.DateTime> qt_deleteDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ContractualInformationByClient> ContractualInformationByClient { get; set; }

}

}
