
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class RulesByMovement
{

    public int rlm_id { get; set; }

    public Nullable<int> m_id { get; set; }

    public Nullable<int> rlm_order { get; set; }

    public Nullable<int> rlm_field_1 { get; set; }

    public Nullable<int> rlm_op_1 { get; set; }

    public Nullable<int> rlm_field_2 { get; set; }

    public Nullable<int> rlm_op_2 { get; set; }

    public Nullable<int> rlm_field_3 { get; set; }

    public Nullable<System.DateTime> rlm_registrationDate { get; set; }

    public Nullable<System.DateTime> rlm_updateDate { get; set; }

    public Nullable<System.DateTime> rlm_deleteDate { get; set; }



    public virtual FieldsToOperate FieldsToOperate { get; set; }

    public virtual FieldsToOperate FieldsToOperate1 { get; set; }

    public virtual FieldsToOperate FieldsToOperate2 { get; set; }

    public virtual Movement Movement { get; set; }

    public virtual Operations Operations { get; set; }

    public virtual Operations Operations1 { get; set; }

}

}
