
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class Taxes
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Taxes()
    {

        this.TaxesByMaintenanceItem = new HashSet<TaxesByMaintenanceItem>();

    }


    public int tax_id { get; set; }

    public string tax_name { get; set; }

    public string tax_desccription { get; set; }

    public int tax_percentValue { get; set; }

    public Nullable<bool> tax_state { get; set; }

    public Nullable<System.DateTime> tax_registrationDate { get; set; }

    public Nullable<System.DateTime> tax_updateDate { get; set; }

    public Nullable<System.DateTime> tax_deleteDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TaxesByMaintenanceItem> TaxesByMaintenanceItem { get; set; }

}

}
