
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class transactions
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public transactions()
    {

        this.LOG_TRX = new HashSet<LOG_TRX>();

        this.observationsByTransaction = new HashSet<observationsByTransaction>();

        this.transactionDetail = new HashSet<transactionDetail>();

        this.transactionDetail1 = new HashSet<transactionDetail>();

        this.transactionItems = new HashSet<transactionItems>();

    }


    public int trx_id { get; set; }

    public Nullable<int> trx_consecutive { get; set; }

    public Nullable<int> m_id { get; set; }

    public Nullable<int> trxst_id { get; set; }

    public Nullable<double> trx_value { get; set; }

    public Nullable<int> usu_id { get; set; }

    public Nullable<bool> trx_state { get; set; }

    public Nullable<System.DateTime> trx_registrationDate { get; set; }

    public Nullable<int> cli_id { get; set; }

    public Nullable<System.DateTime> trx_updateDate { get; set; }

    public Nullable<System.DateTime> trx_deleteDate { get; set; }

    public Nullable<double> trx_taxesValue { get; set; }

    public string trx_code { get; set; }

    public Nullable<double> trx_valueWithoutDiscount { get; set; }

    public Nullable<double> trx_discountValue { get; set; }

    public Nullable<double> trx_valueWithDiscountWithoutTaxes { get; set; }



    public virtual Client Client { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LOG_TRX> LOG_TRX { get; set; }

    public virtual Movement Movement { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<observationsByTransaction> observationsByTransaction { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<transactionDetail> transactionDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<transactionDetail> transactionDetail1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<transactionItems> transactionItems { get; set; }

    public virtual transactionState transactionState { get; set; }

}

}
