
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class transactionDetail
{

    public int trxdt_id { get; set; }

    public Nullable<int> trx_id { get; set; }

    public Nullable<int> veh_id { get; set; }

    public Nullable<int> deal_id { get; set; }

    public Nullable<int> bra_id { get; set; }

    public Nullable<int> mr_id { get; set; }

    public Nullable<int> cntr_id { get; set; }

    public Nullable<int> usu_approbation { get; set; }

    public Nullable<int> usu_reject { get; set; }

    public Nullable<int> usu_anulation { get; set; }

    public Nullable<System.DateTime> trx_rejectDate { get; set; }

    public Nullable<System.DateTime> trx_approbationDate { get; set; }

    public Nullable<System.DateTime> trx_anulationDate { get; set; }

    public Nullable<int> trx_relation_id { get; set; }

    public Nullable<int> usu_ending { get; set; }

    public Nullable<System.DateTime> trx_endingDate { get; set; }



    public virtual branch branch { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual Dealer Dealer { get; set; }

    public virtual maintenanceRoutine maintenanceRoutine { get; set; }

    public virtual transactions transactions { get; set; }

    public virtual Vehicle Vehicle { get; set; }

    public virtual transactions transactions1 { get; set; }

    public virtual Users Users { get; set; }

}

}
