
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class transactionItems
{

    public int trxit_id { get; set; }

    public Nullable<int> trx_id { get; set; }

    public Nullable<int> mi_id { get; set; }

    public Nullable<float> mi_amount { get; set; }

    public Nullable<float> mi_referencePrice { get; set; }

    public Nullable<float> mi_totalPrice { get; set; }

    public Nullable<double> mi_taxesValue { get; set; }

    public Nullable<double> mi_valueWithoutDiscount { get; set; }

    public Nullable<double> mi_discountValue { get; set; }

    public Nullable<double> mi_valueWithDiscountWithoutTaxes { get; set; }



    public virtual MaintenanceItem MaintenanceItem { get; set; }

    public virtual transactions transactions { get; set; }

}

}
