
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class transactionState
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public transactionState()
    {

        this.transactions = new HashSet<transactions>();

    }


    public int trxst_id { get; set; }

    public string trxst_name { get; set; }

    public string trxst_description { get; set; }

    public Nullable<bool> trxst_state { get; set; }

    public Nullable<System.DateTime> trxst_registrationDate { get; set; }

    public Nullable<System.DateTime> trxst_updateDate { get; set; }

    public Nullable<System.DateTime> trxst_deleteDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<transactions> transactions { get; set; }

}

}
