//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_FleetService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int usr_id { get; set; }
        public string usr_name { get; set; }
        public string usr_password { get; set; }
        public int grp_id { get; set; }
        public string usr_firstName { get; set; }
        public string usr_lastName { get; set; }
        public Nullable<int> cli_id { get; set; }
        public Nullable<int> deal_id { get; set; }
        public Nullable<int> cpn_id { get; set; }
        public string email { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Client Client { get; set; }
        public virtual Company Company { get; set; }
        public virtual Dealer Dealer { get; set; }
    }
}
