
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class Users
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Users()
    {

        this.observationsByTransaction = new HashSet<observationsByTransaction>();

        this.transactionDetail = new HashSet<transactionDetail>();

        this.ContractualInformationByClient = new HashSet<ContractualInformationByClient>();

    }


    public int usr_id { get; set; }

    public string usr_name { get; set; }

    public string usr_password { get; set; }

    public int grp_id { get; set; }

    public string usr_firstName { get; set; }

    public string usr_lastName { get; set; }

    public Nullable<int> cli_id { get; set; }

    public Nullable<int> deal_id { get; set; }

    public Nullable<int> cpn_id { get; set; }



    public virtual Groups Groups { get; set; }

    public virtual Groups Groups1 { get; set; }

    public virtual Groups Groups2 { get; set; }

    public virtual Company Company { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<observationsByTransaction> observationsByTransaction { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<transactionDetail> transactionDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ContractualInformationByClient> ContractualInformationByClient { get; set; }

}

}
