//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_FleetService
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicleState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehicleState()
        {
            this.Vehicle = new HashSet<Vehicle>();
        }
    
        public int vs_id { get; set; }
        public string vs_name { get; set; }
        public Nullable<bool> vs_state { get; set; }
        public Nullable<System.DateTime> vs_registrationDate { get; set; }
        public Nullable<System.DateTime> vs_updateDate { get; set; }
        public Nullable<System.DateTime> vs_deleteDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicle { get; set; }
    }
}
