
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO_FleetService
{

using System;
    using System.Collections.Generic;
    
public partial class VehicleBrand
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public VehicleBrand()
    {

        this.VehicleModel = new HashSet<VehicleModel>();

    }


    public int vb_id { get; set; }

    public string vb_name { get; set; }

    public Nullable<bool> vb_state { get; set; }

    public Nullable<System.DateTime> vb_registrationDate { get; set; }

    public Nullable<System.DateTime> vb_updateDate { get; set; }

    public Nullable<System.DateTime> vb_deleteDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VehicleModel> VehicleModel { get; set; }

}

}
