//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_FleetService
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiclesByContract
    {
        public int vehcntr_id { get; set; }
        public Nullable<int> veh_id { get; set; }
        public Nullable<int> cntr_id { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
